name = "yonder-ynab"
main = "build/index.js"
compatibility_date = "2026-01-02"

[build]
command = "cargo install -q worker-build@^0.7 && worker-build --release"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
